# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: ibmstocktrader
  name: tradr
  tag: latest
  pullPolicy: Always
  containerPort: 3000
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
service:
  # Change this to ClusterIP before releasing charts so microservices can only be reached through the ingress
  type: NodePort
  servicePort:
    port: 3000
    nodePort:
secret:
  oidc:
    create: false
    secret_name: stocktrader-oidc
    # auth: https://idaas.iam.ibm.com/idaas/oidc/endpoint/default/authorize
    auth: aHR0cHM6Ly9pZGFhcy5pYW0uaWJtLmNvbS9pZGFhcy9vaWRjL2VuZHBvaW50L2RlZmF1bHQvYXV0aG9yaXpl
    # Your IBMid SSO ClientId
    id:
    # issuer: https://idaas.iam.ibm.com
    issuer: aHR0cHM6Ly9pZGFhcy5pYW0uaWJtLmNvbQ==
    # Points to an entry in the keystore for the key to encrypt communications
    # to the IBMid server. As a result, we can only configure the IBMid production server.
    # key: blueidprod.
    key: Ymx1ZWlkcHJvZA==
    # name: IBMid
    name: SUJNaWQ=
    # Callback host and port number. This is the redirect URI the Trader BFF microservice sends with
    # its requests. This redirect URI must be configured in the IBMid Client Configuration.
    # The redirect URI looks like:
    # https://<ICP_proxy_ip>:<Trader_BFF_NodePort>/ibm/api/social-login/redirect/IBMid
    # Not needed by this Tradr microservice as it uses the ingress_host_secret.yaml for the redirect URI
    nodeport:
    # Your IBMid SSO clientSecret
    secret:
    # token: https://idaas.iam.ibm.com/idaas/oidc/endpoint/default/token
    token: aHR0cHM6Ly9pZGFhcy5pYW0uaWJtLmNvbS9pZGFhcy9vaWRjL2VuZHBvaW50L2RlZmF1bHQvdG9rZW4=
  jwt:
    create: false
    secret_name: stocktrader-jwt
    # audience: stock-trader
    audience: c3RvY2stdHJhZGVy
    # issuer: http://stock-trader.ibm.com
    issuer: aHR0cDovL3N0b2NrLXRyYWRlci5pYm0uY29t
  ingress_host:
    create: false
    secret_name: strocktrader-ingress-host
    # Stocktrader host ip and port
    host:
