{{- if .Values.secret.oidc.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.oidc.secret_name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Chart.Name }}
type: Opaque
data:
  auth: {{ .Values.secret.oidc.auth }}
  id: {{ .Values.secret.oidc.id }}
  issuer: {{ .Values.secret.oidc.issuer }}
  key: {{ .Values.secret.oidc.key }}
  name: {{ .Values.secret.oidc.name }}
  nodeport: {{ .Values.secret.oidc.nodeport }}
  secret: {{ .Values.secret.oidc.secret }}
  token: {{ .Values.secret.oidc.token }}
{{- end }}
