apiVersion: v1
kind: Service
metadata:
  name: tradr-service
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.servicePort.port }}
      nodePort: {{ .Values.service.servicePort.nodePort }}
  selector:
    app: "{{ .Release.Name }}-{{ .Chart.Name }}-selector"
